version: '3'
services:
  mongodb:
    image: mongo:8.0
    container_name: node-mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
      - api-todo  

  todo-api-node:
    container_name: backend
    build: .
    ports:
      - "3002:3000"
    environment:
      MONGO_URI: mongodb://node-mongo:27017/node-api
    depends_on:
      - mongodb
    networks:
      - api-todo  
networks:
  api-todo:
